package com.climasys.admission.service;

import com.climasys.admission.dto.AdmissionCard;
import com.climasys.admission.dto.AdmissionCardDTO;
import com.climasys.admission.dto.AdmissionCardRequest;
import com.climasys.admission.repository.AdmissionCardRepository;
import com.climasys.entity.AdmissionData;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Service class for admission card operations
 * Handles business logic for patient admission information
 */
@Service
@Transactional
public class AdmissionCardService {
    
    private static final Logger logger = LoggerFactory.getLogger(AdmissionCardService.class);
    
    @Autowired
    private AdmissionCardRepository admissionCardRepository;
    
    /**
     * Get all admission cards (list of admitted patients)
     * 
     * @param patientId Patient ID (optional, can be null)
     * @param doctorId Doctor ID (optional, can be null - if null, returns all doctors for the clinic)
     * @param clinicId Clinic ID
     * @return List of admission cards
     */
    @Transactional(readOnly = true)
    public List<AdmissionCardDTO> getAllAdmissionCards(String patientId, String doctorId, String clinicId) {
        logger.info("Getting admission cards for doctor: {}, clinic: {}, patient: {}", 
                    doctorId != null ? doctorId : "ALL", clinicId, patientId != null ? patientId : "ALL");
        
        List<Map<String, Object>> results = admissionCardRepository
                .findAllAdmissionCards(patientId, doctorId, clinicId);
        
        List<AdmissionCardDTO> admissionCards = results.stream()
                .map(this::mapToDTO)
                .collect(Collectors.toList());
        
        logger.info("Retrieved {} admission card(s)", admissionCards.size());
        return admissionCards;
    }
    
    /**
     * Search admission cards by patient ID, name, or contact
     * 
     * @param searchStr Search string
     * @param doctorId Doctor ID (optional, can be null - if null, searches all doctors for the clinic)
     * @param clinicId Clinic ID
     * @return List of matching admission cards
     */
    @Transactional(readOnly = true)
    public List<AdmissionCardDTO> searchAdmissionCards(String searchStr, String doctorId, String clinicId) {
        logger.info("Searching admission cards for: '{}', doctor: {}, clinic: {}", 
                    searchStr, doctorId != null ? doctorId : "ALL", clinicId);
        
        List<Map<String, Object>> results = admissionCardRepository
                .searchAdmissionCards(searchStr, doctorId, clinicId);
        
        List<AdmissionCardDTO> admissionCards = results.stream()
                .map(this::mapToDTO)
                .collect(Collectors.toList());
        
        logger.info("Found {} matching admission card(s)", admissionCards.size());
        return admissionCards;
    }
    
    /**
     * Insert or update admission card
     * Replicates USP_Insert_AdmissionCard
     */
    public Map<String, Object> saveAdmissionCard(AdmissionCardRequest request) {
        logger.info("Saving admission card for patient: {}, IPD: {}", 
                    request.getPatientId(), request.getIpdRefNo());
        
        Map<String, Object> response = new HashMap<>();
        
        try {
            String ipdRefNo = request.getIpdRefNo();
            
            // Check if admission already exists (only if ipdRefNo is provided)
            boolean exists = false;
            if (ipdRefNo != null && !ipdRefNo.trim().isEmpty()) {
                exists = admissionCardRepository.existsByCompositeKey(
                    request.getPatientId(),
                    request.getClinicId(),
                    ipdRefNo
                );
            }
            
            if (!exists) {
                // Insert new admission
                AdmissionData admission = new AdmissionData();
                admission.setPatientId(request.getPatientId());
                admission.setDoctorId(request.getDoctorId());
                admission.setClinicId(request.getClinicId());
                // Note: IPD_RefNo should be auto-generated by database trigger or sequence
                // For now, using the provided value or empty string
                admission.setIpdRefno(ipdRefNo != null ? ipdRefNo : "");
                admission.setRelativeName(request.getRelativeName());
                admission.setRelation(request.getRelation());
                admission.setContactNo(request.getContactNo());
                admission.setAdmissionDate(request.getAdmissionDate());
                admission.setAdmissionTime(request.getAdmissionTime());
                admission.setReasonOfAdmission(request.getReasonOfAdmission());
                admission.setDepartment(request.getDepartment());
                admission.setIsInsurance(request.getIsInsurance() != null ? request.getIsInsurance() : false);
                admission.setInsuranceDetails(request.getInsuranceDetails());
                admission.setTreatingDoctor(request.getTreatingDoctor());
                admission.setConsultantDoctor(request.getConsultingDoctor());
                admission.setIpdFileNo(request.getIpdFileNo());
                admission.setRoomNo(request.getRoomNo());
                admission.setBedNo(request.getBedNo());
                admission.setPackageRemarks(request.getPackageRemarks());
                admission.setShiftId(request.getShiftId());
                admission.setCreatedByName(request.getLoginId());
                admission.setCreatedOn(java.time.LocalDate.now());
                admission.setReferredDoctor(request.getReferredDoctor());
                admission.setCommentsNote(request.getCommentsNote());
                admission.setInsuranceCompanyId(request.getInsuranceCompanyId());
                
                AdmissionData saved = admissionCardRepository.save(admission);
                
                response.put("saveStatus", 1);
                response.put("message", "Admission card saved successfully");
                response.put("ipdRefNo", saved.getIpdRefno());
                logger.info("Inserted new admission card with IPD: {}", saved.getIpdRefno());
                
            } else {
                // Update existing admission
                AdmissionData admission = admissionCardRepository.findById(
                    new com.climasys.entity.AdmissionDataId(
                        request.getPatientId(),
                        request.getDoctorId(),
                        request.getClinicId(),
                        ipdRefNo
                    )
                ).orElseThrow(() -> new RuntimeException("Admission not found"));
                
                admission.setRelativeName(request.getRelativeName());
                admission.setRelation(request.getRelation());
                admission.setContactNo(request.getContactNo());
                admission.setAdmissionDate(request.getAdmissionDate());
                admission.setAdmissionTime(request.getAdmissionTime());
                admission.setReasonOfAdmission(request.getReasonOfAdmission());
                admission.setDepartment(request.getDepartment());
                admission.setIsInsurance(request.getIsInsurance());
                admission.setInsuranceDetails(request.getInsuranceDetails());
                admission.setTreatingDoctor(request.getTreatingDoctor());
                admission.setConsultantDoctor(request.getConsultingDoctor());
                admission.setIpdFileNo(request.getIpdFileNo());
                admission.setRoomNo(request.getRoomNo());
                admission.setBedNo(request.getBedNo());
                admission.setPackageRemarks(request.getPackageRemarks());
                admission.setModifiedByName(request.getLoginId());
                admission.setModifiedOn(java.time.LocalDate.now());
                admission.setReferredDoctor(request.getReferredDoctor());
                admission.setCommentsNote(request.getCommentsNote());
                admission.setInsuranceCompanyId(request.getInsuranceCompanyId());
                
                admissionCardRepository.save(admission);
                
                response.put("saveStatus", 2);
                response.put("message", "Admission card updated successfully");
                logger.info("Updated admission card with IPD: {}", ipdRefNo);
            }
            
            response.put("success", true);
            
        } catch (Exception e) {
            logger.error("Error saving admission card", e);
            response.put("success", false);
            response.put("error", e.getMessage());
        }
        
        return response;
    }
    
    /**
     * Convert AdmissionCard projection to DTO
     */
    private AdmissionCardDTO convertToDTO(AdmissionCard admissionCard) {
        return new AdmissionCardDTO(
            admissionCard.getSerialNumber(),
            admissionCard.getPatientName(),
            admissionCard.getAdmissionIpdNo(),
            admissionCard.getIpdFileNo(),
            admissionCard.getAdmissionDate(),
            admissionCard.getReasonOfAdmission(),
            admissionCard.getDischargeDate(),
            admissionCard.getInsurance(),
            admissionCard.getCompany(),
            admissionCard.getAdvanceRs(),
            admissionCard.getPatientId()
        );
    }
    
    /**
     * Map database result to DTO
     */
    private AdmissionCardDTO mapToDTO(Map<String, Object> result) {
        AdmissionCardDTO dto = new AdmissionCardDTO();
        
        dto.setSerialNumber(getIntegerValue(result, "serialnumber"));
        dto.setPatientName(getStringValue(result, "patientname"));
        dto.setAdmissionIpdNo(getStringValue(result, "admissionipdno"));
        dto.setIpdFileNo(getStringValue(result, "ipdfileno"));
        dto.setAdmissionDate(getStringValue(result, "admissiondate"));
        dto.setReasonOfAdmission(getStringValue(result, "reasonofadmission"));
        dto.setDischargeDate(getStringValue(result, "dischargedate"));
        dto.setInsurance(getStringValue(result, "insurance"));
        dto.setCompany(getStringValue(result, "company"));
        dto.setAdvanceRs(getBigDecimalValue(result, "advancers"));
        dto.setPatientId(getStringValue(result, "patientid"));
        
        return dto;
    }
    
    private String getStringValue(Map<String, Object> result, String key) {
        Object value = result.get(key);
        return value != null ? value.toString() : "";
    }
    
    private Integer getIntegerValue(Map<String, Object> result, String key) {
        Object value = result.get(key);
        if (value == null) {
            return 0;
        }
        if (value instanceof Integer) {
            return (Integer) value;
        }
        if (value instanceof Number) {
            return ((Number) value).intValue();
        }
        if (value instanceof Long) {
            return ((Long) value).intValue();
        }
        return 0;
    }
    
    private BigDecimal getBigDecimalValue(Map<String, Object> result, String key) {
        Object value = result.get(key);
        if (value == null) {
            return BigDecimal.ZERO;
        }
        if (value instanceof BigDecimal) {
            return (BigDecimal) value;
        }
        if (value instanceof Number) {
            return new BigDecimal(value.toString());
        }
        return BigDecimal.ZERO;
    }
}

