# Development Environment Configuration
spring:
  application:
    name: climasys-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/climasys_dev_new
    username: postgres
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        connection:
          provider_disables_autocommit: true
        jdbc:
          time_zone: UTC
        order_inserts: true
        order_updates: true
        batch_size: 25
        hbm2ddl:
          auto: update
  sql:
    init:
      mode: never

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.climasys: DEBUG

# Development-specific settings
climasys:
  encryption:
    key: ${CLIMASYS_ENCRYPTION_KEY:PA1ANDE61INI6}
  jwt:
    secret: ${JWT_SECRET:dev-secret-key-change-in-production}
    expiration: 86400000 # 24 hours
  database:
    tables:
      patient_master: patient_master
      doctor_master: doctor_master
      clinic_master: clinic_master
      appointment_master: appointment_master
      patient_queue: patient_queue
      patient_visits: patient_visits
