spring:
  application:
    name: climasys-backend see data 
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/climasys_dev_new?currentSchema=public
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        connection:
          provider_disables_autocommit: true
        jdbc:
          time_zone: UTC
        order_inserts: true
        order_updates: true
        batch_size: 25

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.jdbc: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO
    com.climasys: INFO

climasys:
  encryption:
    key: ${CLIMASYS_ENCRYPTION_KEY:PA1ANDE61INI6}
  jwt:
    secret: ${JWT_SECRET:your-jwt-secret}
    expiration: 86400000
  database:
    tables:
      patient_master: patient_master
      doctor_master: doctor_master
      clinic_master: clinic_master
      appointment_master: appointment_master
      patient_queue: patient_queue
      patient_visits: patient_visits

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: true

