# PostgreSQL Database Configuration
spring:
  application:
    name: climasys-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:climasys_dev_new}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        connection:
          provider_disables_autocommit: true
        jdbc:
          time_zone: UTC
        order_inserts: true
        order_updates: true
        batch_size: 25
        hbm2ddl:
          auto: validate

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.jdbc: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO
    com.climasys: INFO

climasys:
  encryption:
    key: ${CLIMASYS_ENCRYPTION_KEY:PA1ANDE61INI6}
  jwt:
    secret: ${JWT_SECRET:your-jwt-secret}
    expiration: 86400000
  database:
    tables:
      patient_master: patient_master
      doctor_master: doctor_master
      clinic_master: clinic_master
      appointment_master: appointment_master
      patient_queue: patient_queue
      patient_visits: patient_visits
