# Production Environment Configuration
spring:
  application:
    name: climasys-backend
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};encrypt=true;trustServerCertificate=true;databaseName=${DB_NAME:Climasys-Prod}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: false

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.springframework.jdbc: WARN
    com.zaxxer.hikari: WARN
    org.hibernate.SQL: WARN
    com.climasys: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/climasys-backend.log

# Production-specific settings
climasys:
  encryption:
    key: ${CLIMASYS_ENCRYPTION_KEY}
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000 # 1 hour
