# MySQL Database Configuration
spring:
  application:
    name: climasys-backend
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:climasys}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.jdbc: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO
    com.climasys: INFO

climasys:
  encryption:
    key: ${CLIMASYS_ENCRYPTION_KEY:PA1ANDE61INI6}
  jwt:
    secret: ${JWT_SECRET:your-jwt-secret}
    expiration: 86400000
