
-- =====================================================
-- Comprehensive SQL Server Data Extraction Queries
-- Generated by comprehensive_migration_framework.py
-- =====================================================


-- Table: Clinic_Master
SELECT Doctor_ID, Clinic_ID, Clinic_Name, Clinic_Address, Country_ID, State_ID, City_ID, Area_ID, Pincode, Tips, News, Phone_No, Fax_No, Created_On, CreatedBy_Name, Modified_On, ModifiedBy_Name, IS_Print
FROM [Climasys-00010].[dbo].[Clinic_Master];

-- Table: Doctor_Clinic_Shift
SELECT Doctor_ID, Clinic_ID, Shift_ID
FROM [Climasys-00010].[dbo].[Doctor_Clinic_Shift];

-- Table: Doctor_Master
SELECT Doctor_ID, Prefix, First_Name, Middle_Name, Last_Name, Doctor_Photo, Registration_No, Speciality, Residential_No, Practising_Year, Mobile_1, Mobile_2, Emergency_Number, Wapp_No, EmailID, Doctor_Qual, Residential_Add1, Residential_Add2, Country_ID, State_ID, City_ID, Area_ID, Profile_Image, Created_On, CreatedBy_Name, Modified_On, ModifiedBy_Name, Base_Location, IPD_DR, OPD_DR
FROM [Climasys-00010].[dbo].[Doctor_Master];

-- Table: Doctor_Model
SELECT Doctor_ID, Clinic_ID, Model_ID
FROM [Climasys-00010].[dbo].[Doctor_Model];

-- Table: Gender_Master
SELECT ID
FROM [Climasys-00010].[dbo].[Gender_Master];

-- Table: Language_Master
SELECT Language_Id, Language_Name, Is_Default
FROM [Climasys-00010].[dbo].[Language_Master];

-- Table: License_Key
SELECT Doctor_ID, Clinic_ID, Installation_Date, Last_Renewal_Date, License_Validity, Valid_From, Valid_To, VerNo, License_Key, start_verification
FROM [Climasys-00010].[dbo].[License_Key];

-- Table: Model
SELECT Model_ID, Model_Number, Model_Description
FROM [Climasys-00010].[dbo].[Model];

-- Table: Model_Config_Params
SELECT Model_ID, Config_ID, IS_Enabled
FROM [Climasys-00010].[dbo].[Model_Config_Params];

-- Table: Patient_Master
SELECT ID, Doctor_ID, Folder_No, First_Name, Middle_Name, Last_Name, Reports_Received, Email_ID, Gender_ID, Address_1, Address_2, Country_ID, State_ID, City_ID, Area_ID, Pincode, Date_Of_Birth, Age_Given, Weight_IN_KGS, Height_In_CMS, Occupation_ID, BloodGroup_ID, Residential_No, Mobile_1, Mobile_2, Emergency_Number, Emergency_Name, Patient_Last_Visit_No, Date_Of_Registration, Manual_Registration_Year, Registration_Status, Folder_Path, Created_On, CreatedBy_Name, Modified_On, ModifiedBy_Name, Refer_ID, Refer_Doctor_Details, Marital_Status_ID, Doctor_Address, Doctor_Mobile, Doctor_Email, Clinic_ID
FROM [Climasys-00010].[dbo].[Patient_Master];

-- Table: Patient_Visits
SELECT Doctor_ID, Clinic_ID, Shift_ID, Patient_ID, Patient_Visit_No, Visit_Date, Folder_No, Visit_Time, Financial_Year, Status_ID, Weight_IN_KGS, Reports_Asked, Reports_Received, Asthama, Tuberculosis, Hypertension, Diabetes, Cholestrol, Allergy_dtls, Habits_Comments, Tobaco, Smoking, Alchohol, IHD, TH, Height_In_CMS, Pulse, Blood_Pressure, Fees_To_Collect, Fees_Collected, Instructions, Appointment_Sr_No, Patient_Last_Visit_No, On_Call_Status, Created_On, CreatedBy_Name, Modified_On, ModifiedBy_Name, Delete_Flag, Comment, Observation, In_Person, Original_Billed_Amount, Sugar, THtext, Offline_Reason, Offline_Flag, Symptom_Comment, Impression, Payment_By_ID, Attended_By, Payment_Remark, Attended_By_ID, follow_up, Receipt_Number, Is_follow_Up, Current_Medicines, Visit_Comments, Current_Complaints, Is_Submit_Patient_Visit_Details, Is_Submit_Patient_LabTest, Receipt_Type, TPR, Important_Findings, Additional_Comments, Systemic, Odeama, Pallor, IS_Submit_Gynec_Details, GC, FMP, PRMC, PAMC, LMP, Obstetrics_History, Surgical_History_Past_History, Gynec_Additional_Comments, Pregnant, EDD, follow_up_type, Follow_Up_Date, Addendum, From_time, follow_up_Comment, Treatment_comment, Treatment_plan, Doctor_notes, plan, Notes, Followup_After, Schedule, Additional_Instructions, Impression_Finding, Discount, Original_Discount, Complaints_by_Patient_Per_Visit, CAT_ID, Online_Appointment_Time, Refer_ID, Refer_Doctor_Details, Doctor_Address, Doctor_Mobile, Doctor_Email
FROM [Climasys-00010].[dbo].[Patient_Visits];

-- Table: Role_Master
SELECT Role_Id, Role_Name, Created_On, CreatedBy_Name, Modified_On, ModifiedBy_Name
FROM [Climasys-00010].[dbo].[Role_Master];

-- Table: Shift_Master
SELECT Shift_ID, Description, Shift_Day, Start_Time, End_Time, Created_On, CreatedBy_Name, Modified_On, ModifiedBy_Name
FROM [Climasys-00010].[dbo].[Shift_Master];

-- Table: System_Params
SELECT Doctor_ID, Default_Fees, Compounder_Overwrite, Default_Clinic_ID, Default_Prescription_Count, Default_Autorefresh_Timer, Previous_Pharama_CompanyVisits, Previous_Visits_MR, Reminder_Attachements_Allowed, Medicines_By_MR, Show_Diseases, Show_Dressings, Show_Medicines, Show_MR, Show_Procedure, Show_Daily_Collection, Treatment_Details, Type_Of_Service, Show_Patient_Visit_Details, Comprehensive_Billing, Show_TreatmentPlan_Details, Show_IPD, Show_Gynec, Clinic_ID, Show_Financials, Print_Diagnosis_on_Prescription, Copy_Visit, Balance, Audio_Allergy, IS_MAIN_DOCTOR, Show_complaint, Logo_Files, Print_Receipt_Header, Print_Prescription_Header, Print_OPS_Label, Print_Discount_on_Hospital_bill, Print_Advice_label, Print_Generic_Name, Capture_Followup_Text, Copy_prescription, Print_Vitals, Print_Complaints_on_prescriptipon, Print_Examination_on_prescriptipon, Footer_for_Discharge_Card, Print_discharge_Card_header, Show_Services, Default_Prescription_Category
FROM [Climasys-00010].[dbo].[System_Params];

-- Table: User_Master
SELECT ID, Doctor_ID, Is_Active, Login_Id, Password, First_Name, Middle_Name, Last_Name, Residential_Add1, Residential_Add2, Country_ID, State_ID, City_ID, Area_ID, Pin_Code, Phone_No, Mobile_No, Email, Language_Id, User_Photo, Created_On, CreatedBy_Name, Modified_On, ModifiedBy_Name, Clinic_ID, Base_Location, Default_Doctor, Default_Doctors_Department, Show_Daily_Collection, BackupDrive
FROM [Climasys-00010].[dbo].[User_Master];

-- Table: User_Role
SELECT Doctor_ID, Clinic_ID, User_ID, Role_Id, Is_Default_Clinic, Created_On, CreatedBy_Name, Modified_On, ModifiedBy_Name
FROM [Climasys-00010].[dbo].[User_Role];

-- Table: Visit_Prescription_Overwrite
SELECT Doctor_ID, Clinic_ID, Shift_ID, Patient_ID, Patient_Visit_No, Visit_Date, Brand_Name, Medicine_Name, CatSub_Description, Cat_Short_Name, Marketed_By, Morning, Afternoon, Night, No_Of_Days, Instruction, Created_On, CreatedBy_Name, Modified_On, ModifiedBy_Name, Delete_Indicator, Delete_Flag, Sequence_Id
FROM [Climasys-00010].[dbo].[Visit_Prescription_Overwrite];
