-- =====================================================
-- Complete SQL Server Data Extraction Queries for All 150 Tables
-- Generated by extract_all_150_tables.py
-- Date: 2025-09-16 09:50:46
-- =====================================================

-- Instructions:
-- 1. Run these queries on your SQL Server instance
-- 2. Export results to CSV files in the extracted_data/ directory
-- 3. Use the import script to load data into PostgreSQL


-- Table: Language_Master
-- Export to: extracted_data/Language_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Language_Master]
ORDER BY 1;

-- Table: Role_Master
-- Export to: extracted_data/Role_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Role_Master]
ORDER BY 1;

-- Table: Gender_Master
-- Export to: extracted_data/Gender_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Gender_Master]
ORDER BY 1;

-- Table: Blood_Group_Master
-- Export to: extracted_data/Blood_Group_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Blood_Group_Master]
ORDER BY 1;

-- Table: Doctor_Master
-- Export to: extracted_data/Doctor_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Doctor_Master]
ORDER BY 1;

-- Table: Clinic_Master
-- Export to: extracted_data/Clinic_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Clinic_Master]
ORDER BY 1;

-- Table: User_Master
-- Export to: extracted_data/User_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[User_Master]
ORDER BY 1;

-- Table: Patient_Master
-- Export to: extracted_data/Patient_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Patient_Master]
ORDER BY 1;

-- Table: Shift_Master
-- Export to: extracted_data/Shift_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Shift_Master]
ORDER BY 1;

-- Table: Model
-- Export to: extracted_data/Model.csv
SELECT *
FROM [Climasys-00010].[dbo].[Model]
ORDER BY 1;

-- Table: Model_Config_Params
-- Export to: extracted_data/Model_Config_Params.csv
SELECT *
FROM [Climasys-00010].[dbo].[Model_Config_Params]
ORDER BY 1;

-- Table: System_Params
-- Export to: extracted_data/System_Params.csv
SELECT *
FROM [Climasys-00010].[dbo].[System_Params]
ORDER BY 1;

-- Table: License_Key
-- Export to: extracted_data/License_Key.csv
SELECT *
FROM [Climasys-00010].[dbo].[License_Key]
ORDER BY 1;

-- Table: Medicine_Master
-- Export to: extracted_data/Medicine_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Medicine_Master]
ORDER BY 1;

-- Table: Prescription_Master
-- Export to: extracted_data/Prescription_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Prescription_Master]
ORDER BY 1;

-- Table: Patient_Visits
-- Export to: extracted_data/Patient_Visits.csv
SELECT *
FROM [Climasys-00010].[dbo].[Patient_Visits]
ORDER BY 1;

-- Table: Patient_Family
-- Export to: extracted_data/Patient_Family.csv
SELECT *
FROM [Climasys-00010].[dbo].[Patient_Family]
ORDER BY 1;

-- Table: Patient_Insurance
-- Export to: extracted_data/Patient_Insurance.csv
SELECT *
FROM [Climasys-00010].[dbo].[Patient_Insurance]
ORDER BY 1;

-- Table: Patient_Lab_Tests
-- Export to: extracted_data/Patient_Lab_Tests.csv
SELECT *
FROM [Climasys-00010].[dbo].[Patient_Lab_Tests]
ORDER BY 1;

-- Table: Patient_History
-- Export to: extracted_data/Patient_History.csv
SELECT *
FROM [Climasys-00010].[dbo].[Patient_History]
ORDER BY 1;

-- Table: Patient_Allergies
-- Export to: extracted_data/Patient_Allergies.csv
SELECT *
FROM [Climasys-00010].[dbo].[Patient_Allergies]
ORDER BY 1;

-- Table: Patient_Medications
-- Export to: extracted_data/Patient_Medications.csv
SELECT *
FROM [Climasys-00010].[dbo].[Patient_Medications]
ORDER BY 1;

-- Table: Patient_Vitals
-- Export to: extracted_data/Patient_Vitals.csv
SELECT *
FROM [Climasys-00010].[dbo].[Patient_Vitals]
ORDER BY 1;

-- Table: Patient_Documents
-- Export to: extracted_data/Patient_Documents.csv
SELECT *
FROM [Climasys-00010].[dbo].[Patient_Documents]
ORDER BY 1;

-- Table: Patient_Appointments
-- Export to: extracted_data/Patient_Appointments.csv
SELECT *
FROM [Climasys-00010].[dbo].[Patient_Appointments]
ORDER BY 1;

-- Table: Patient_Billing
-- Export to: extracted_data/Patient_Billing.csv
SELECT *
FROM [Climasys-00010].[dbo].[Patient_Billing]
ORDER BY 1;

-- Table: Doctor_Clinic_Shift
-- Export to: extracted_data/Doctor_Clinic_Shift.csv
SELECT *
FROM [Climasys-00010].[dbo].[Doctor_Clinic_Shift]
ORDER BY 1;

-- Table: Doctor_Model
-- Export to: extracted_data/Doctor_Model.csv
SELECT *
FROM [Climasys-00010].[dbo].[Doctor_Model]
ORDER BY 1;

-- Table: Doctor_Specialization
-- Export to: extracted_data/Doctor_Specialization.csv
SELECT *
FROM [Climasys-00010].[dbo].[Doctor_Specialization]
ORDER BY 1;

-- Table: Doctor_Qualification
-- Export to: extracted_data/Doctor_Qualification.csv
SELECT *
FROM [Climasys-00010].[dbo].[Doctor_Qualification]
ORDER BY 1;

-- Table: Doctor_Schedule
-- Export to: extracted_data/Doctor_Schedule.csv
SELECT *
FROM [Climasys-00010].[dbo].[Doctor_Schedule]
ORDER BY 1;

-- Table: Doctor_Availability
-- Export to: extracted_data/Doctor_Availability.csv
SELECT *
FROM [Climasys-00010].[dbo].[Doctor_Availability]
ORDER BY 1;

-- Table: Doctor_Notes
-- Export to: extracted_data/Doctor_Notes.csv
SELECT *
FROM [Climasys-00010].[dbo].[Doctor_Notes]
ORDER BY 1;

-- Table: Doctor_Prescriptions
-- Export to: extracted_data/Doctor_Prescriptions.csv
SELECT *
FROM [Climasys-00010].[dbo].[Doctor_Prescriptions]
ORDER BY 1;

-- Table: Clinic_Schedule
-- Export to: extracted_data/Clinic_Schedule.csv
SELECT *
FROM [Climasys-00010].[dbo].[Clinic_Schedule]
ORDER BY 1;

-- Table: Clinic_Staff
-- Export to: extracted_data/Clinic_Staff.csv
SELECT *
FROM [Climasys-00010].[dbo].[Clinic_Staff]
ORDER BY 1;

-- Table: Clinic_Equipment
-- Export to: extracted_data/Clinic_Equipment.csv
SELECT *
FROM [Climasys-00010].[dbo].[Clinic_Equipment]
ORDER BY 1;

-- Table: Clinic_Rooms
-- Export to: extracted_data/Clinic_Rooms.csv
SELECT *
FROM [Climasys-00010].[dbo].[Clinic_Rooms]
ORDER BY 1;

-- Table: Clinic_Services
-- Export to: extracted_data/Clinic_Services.csv
SELECT *
FROM [Climasys-00010].[dbo].[Clinic_Services]
ORDER BY 1;

-- Table: Clinic_Pricing
-- Export to: extracted_data/Clinic_Pricing.csv
SELECT *
FROM [Climasys-00010].[dbo].[Clinic_Pricing]
ORDER BY 1;

-- Table: Clinic_Inventory
-- Export to: extracted_data/Clinic_Inventory.csv
SELECT *
FROM [Climasys-00010].[dbo].[Clinic_Inventory]
ORDER BY 1;

-- Table: Clinic_Supplies
-- Export to: extracted_data/Clinic_Supplies.csv
SELECT *
FROM [Climasys-00010].[dbo].[Clinic_Supplies]
ORDER BY 1;

-- Table: Billing_Master
-- Export to: extracted_data/Billing_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Billing_Master]
ORDER BY 1;

-- Table: Billing_Details
-- Export to: extracted_data/Billing_Details.csv
SELECT *
FROM [Climasys-00010].[dbo].[Billing_Details]
ORDER BY 1;

-- Table: Payment_Master
-- Export to: extracted_data/Payment_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Payment_Master]
ORDER BY 1;

-- Table: Payment_Details
-- Export to: extracted_data/Payment_Details.csv
SELECT *
FROM [Climasys-00010].[dbo].[Payment_Details]
ORDER BY 1;

-- Table: Invoice_Master
-- Export to: extracted_data/Invoice_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Invoice_Master]
ORDER BY 1;

-- Table: Invoice_Details
-- Export to: extracted_data/Invoice_Details.csv
SELECT *
FROM [Climasys-00010].[dbo].[Invoice_Details]
ORDER BY 1;

-- Table: Receipt_Master
-- Export to: extracted_data/Receipt_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Receipt_Master]
ORDER BY 1;

-- Table: Receipt_Details
-- Export to: extracted_data/Receipt_Details.csv
SELECT *
FROM [Climasys-00010].[dbo].[Receipt_Details]
ORDER BY 1;

-- Table: Financial_Year
-- Export to: extracted_data/Financial_Year.csv
SELECT *
FROM [Climasys-00010].[dbo].[Financial_Year]
ORDER BY 1;

-- Table: Tax_Master
-- Export to: extracted_data/Tax_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Tax_Master]
ORDER BY 1;

-- Table: Discount_Master
-- Export to: extracted_data/Discount_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Discount_Master]
ORDER BY 1;

-- Table: Refund_Master
-- Export to: extracted_data/Refund_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Refund_Master]
ORDER BY 1;

-- Table: Lab_Test_Master
-- Export to: extracted_data/Lab_Test_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Lab_Test_Master]
ORDER BY 1;

-- Table: Lab_Test_Categories
-- Export to: extracted_data/Lab_Test_Categories.csv
SELECT *
FROM [Climasys-00010].[dbo].[Lab_Test_Categories]
ORDER BY 1;

-- Table: Lab_Test_Results
-- Export to: extracted_data/Lab_Test_Results.csv
SELECT *
FROM [Climasys-00010].[dbo].[Lab_Test_Results]
ORDER BY 1;

-- Table: Lab_Test_Reports
-- Export to: extracted_data/Lab_Test_Reports.csv
SELECT *
FROM [Climasys-00010].[dbo].[Lab_Test_Reports]
ORDER BY 1;

-- Table: Lab_Equipment
-- Export to: extracted_data/Lab_Equipment.csv
SELECT *
FROM [Climasys-00010].[dbo].[Lab_Equipment]
ORDER BY 1;

-- Table: Lab_Technicians
-- Export to: extracted_data/Lab_Technicians.csv
SELECT *
FROM [Climasys-00010].[dbo].[Lab_Technicians]
ORDER BY 1;

-- Table: Lab_Samples
-- Export to: extracted_data/Lab_Samples.csv
SELECT *
FROM [Climasys-00010].[dbo].[Lab_Samples]
ORDER BY 1;

-- Table: Lab_Reports
-- Export to: extracted_data/Lab_Reports.csv
SELECT *
FROM [Climasys-00010].[dbo].[Lab_Reports]
ORDER BY 1;

-- Table: Insurance_Company_Master
-- Export to: extracted_data/Insurance_Company_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Insurance_Company_Master]
ORDER BY 1;

-- Table: Insurance_Policy_Master
-- Export to: extracted_data/Insurance_Policy_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Insurance_Policy_Master]
ORDER BY 1;

-- Table: Insurance_Claims
-- Export to: extracted_data/Insurance_Claims.csv
SELECT *
FROM [Climasys-00010].[dbo].[Insurance_Claims]
ORDER BY 1;

-- Table: Insurance_Approvals
-- Export to: extracted_data/Insurance_Approvals.csv
SELECT *
FROM [Climasys-00010].[dbo].[Insurance_Approvals]
ORDER BY 1;

-- Table: Insurance_Rejections
-- Export to: extracted_data/Insurance_Rejections.csv
SELECT *
FROM [Climasys-00010].[dbo].[Insurance_Rejections]
ORDER BY 1;

-- Table: Insurance_Documents
-- Export to: extracted_data/Insurance_Documents.csv
SELECT *
FROM [Climasys-00010].[dbo].[Insurance_Documents]
ORDER BY 1;

-- Table: Appointment_Master
-- Export to: extracted_data/Appointment_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Appointment_Master]
ORDER BY 1;

-- Table: Appointment_Details
-- Export to: extracted_data/Appointment_Details.csv
SELECT *
FROM [Climasys-00010].[dbo].[Appointment_Details]
ORDER BY 1;

-- Table: Appointment_Status
-- Export to: extracted_data/Appointment_Status.csv
SELECT *
FROM [Climasys-00010].[dbo].[Appointment_Status]
ORDER BY 1;

-- Table: Appointment_Reminders
-- Export to: extracted_data/Appointment_Reminders.csv
SELECT *
FROM [Climasys-00010].[dbo].[Appointment_Reminders]
ORDER BY 1;

-- Table: Appointment_Cancellations
-- Export to: extracted_data/Appointment_Cancellations.csv
SELECT *
FROM [Climasys-00010].[dbo].[Appointment_Cancellations]
ORDER BY 1;

-- Table: Appointment_Rescheduling
-- Export to: extracted_data/Appointment_Rescheduling.csv
SELECT *
FROM [Climasys-00010].[dbo].[Appointment_Rescheduling]
ORDER BY 1;

-- Table: Medicine_Categories
-- Export to: extracted_data/Medicine_Categories.csv
SELECT *
FROM [Climasys-00010].[dbo].[Medicine_Categories]
ORDER BY 1;

-- Table: Medicine_Manufacturers
-- Export to: extracted_data/Medicine_Manufacturers.csv
SELECT *
FROM [Climasys-00010].[dbo].[Medicine_Manufacturers]
ORDER BY 1;

-- Table: Medicine_Suppliers
-- Export to: extracted_data/Medicine_Suppliers.csv
SELECT *
FROM [Climasys-00010].[dbo].[Medicine_Suppliers]
ORDER BY 1;

-- Table: Medicine_Inventory
-- Export to: extracted_data/Medicine_Inventory.csv
SELECT *
FROM [Climasys-00010].[dbo].[Medicine_Inventory]
ORDER BY 1;

-- Table: Medicine_Stock
-- Export to: extracted_data/Medicine_Stock.csv
SELECT *
FROM [Climasys-00010].[dbo].[Medicine_Stock]
ORDER BY 1;

-- Table: Medicine_Expiry
-- Export to: extracted_data/Medicine_Expiry.csv
SELECT *
FROM [Climasys-00010].[dbo].[Medicine_Expiry]
ORDER BY 1;

-- Table: Medicine_Returns
-- Export to: extracted_data/Medicine_Returns.csv
SELECT *
FROM [Climasys-00010].[dbo].[Medicine_Returns]
ORDER BY 1;

-- Table: Pharmacy_Master
-- Export to: extracted_data/Pharmacy_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Pharmacy_Master]
ORDER BY 1;

-- Table: Pharmacy_Orders
-- Export to: extracted_data/Pharmacy_Orders.csv
SELECT *
FROM [Climasys-00010].[dbo].[Pharmacy_Orders]
ORDER BY 1;

-- Table: Pharmacy_Deliveries
-- Export to: extracted_data/Pharmacy_Deliveries.csv
SELECT *
FROM [Climasys-00010].[dbo].[Pharmacy_Deliveries]
ORDER BY 1;

-- Table: Visit_Prescription_Overwrite
-- Export to: extracted_data/Visit_Prescription_Overwrite.csv
SELECT *
FROM [Climasys-00010].[dbo].[Visit_Prescription_Overwrite]
ORDER BY 1;

-- Table: Visit_Details
-- Export to: extracted_data/Visit_Details.csv
SELECT *
FROM [Climasys-00010].[dbo].[Visit_Details]
ORDER BY 1;

-- Table: Visit_Notes
-- Export to: extracted_data/Visit_Notes.csv
SELECT *
FROM [Climasys-00010].[dbo].[Visit_Notes]
ORDER BY 1;

-- Table: Visit_Images
-- Export to: extracted_data/Visit_Images.csv
SELECT *
FROM [Climasys-00010].[dbo].[Visit_Images]
ORDER BY 1;

-- Table: Visit_Documents
-- Export to: extracted_data/Visit_Documents.csv
SELECT *
FROM [Climasys-00010].[dbo].[Visit_Documents]
ORDER BY 1;

-- Table: Visit_Followup
-- Export to: extracted_data/Visit_Followup.csv
SELECT *
FROM [Climasys-00010].[dbo].[Visit_Followup]
ORDER BY 1;

-- Table: Visit_Complaints
-- Export to: extracted_data/Visit_Complaints.csv
SELECT *
FROM [Climasys-00010].[dbo].[Visit_Complaints]
ORDER BY 1;

-- Table: Visit_Diagnosis
-- Export to: extracted_data/Visit_Diagnosis.csv
SELECT *
FROM [Climasys-00010].[dbo].[Visit_Diagnosis]
ORDER BY 1;

-- Table: Visit_Treatment
-- Export to: extracted_data/Visit_Treatment.csv
SELECT *
FROM [Climasys-00010].[dbo].[Visit_Treatment]
ORDER BY 1;

-- Table: Visit_Procedures
-- Export to: extracted_data/Visit_Procedures.csv
SELECT *
FROM [Climasys-00010].[dbo].[Visit_Procedures]
ORDER BY 1;

-- Table: Visit_Medications
-- Export to: extracted_data/Visit_Medications.csv
SELECT *
FROM [Climasys-00010].[dbo].[Visit_Medications]
ORDER BY 1;

-- Table: User_Role
-- Export to: extracted_data/User_Role.csv
SELECT *
FROM [Climasys-00010].[dbo].[User_Role]
ORDER BY 1;

-- Table: User_Permissions
-- Export to: extracted_data/User_Permissions.csv
SELECT *
FROM [Climasys-00010].[dbo].[User_Permissions]
ORDER BY 1;

-- Table: User_Sessions
-- Export to: extracted_data/User_Sessions.csv
SELECT *
FROM [Climasys-00010].[dbo].[User_Sessions]
ORDER BY 1;

-- Table: User_Logs
-- Export to: extracted_data/User_Logs.csv
SELECT *
FROM [Climasys-00010].[dbo].[User_Logs]
ORDER BY 1;

-- Table: User_Activity
-- Export to: extracted_data/User_Activity.csv
SELECT *
FROM [Climasys-00010].[dbo].[User_Activity]
ORDER BY 1;

-- Table: Role_Permissions
-- Export to: extracted_data/Role_Permissions.csv
SELECT *
FROM [Climasys-00010].[dbo].[Role_Permissions]
ORDER BY 1;

-- Table: User_Profile
-- Export to: extracted_data/User_Profile.csv
SELECT *
FROM [Climasys-00010].[dbo].[User_Profile]
ORDER BY 1;

-- Table: User_Settings
-- Export to: extracted_data/User_Settings.csv
SELECT *
FROM [Climasys-00010].[dbo].[User_Settings]
ORDER BY 1;

-- Table: User_Preferences
-- Export to: extracted_data/User_Preferences.csv
SELECT *
FROM [Climasys-00010].[dbo].[User_Preferences]
ORDER BY 1;

-- Table: System_Configuration
-- Export to: extracted_data/System_Configuration.csv
SELECT *
FROM [Climasys-00010].[dbo].[System_Configuration]
ORDER BY 1;

-- Table: System_Logs
-- Export to: extracted_data/System_Logs.csv
SELECT *
FROM [Climasys-00010].[dbo].[System_Logs]
ORDER BY 1;

-- Table: System_Backup
-- Export to: extracted_data/System_Backup.csv
SELECT *
FROM [Climasys-00010].[dbo].[System_Backup]
ORDER BY 1;

-- Table: System_Maintenance
-- Export to: extracted_data/System_Maintenance.csv
SELECT *
FROM [Climasys-00010].[dbo].[System_Maintenance]
ORDER BY 1;

-- Table: System_Updates
-- Export to: extracted_data/System_Updates.csv
SELECT *
FROM [Climasys-00010].[dbo].[System_Updates]
ORDER BY 1;

-- Table: System_Alerts
-- Export to: extracted_data/System_Alerts.csv
SELECT *
FROM [Climasys-00010].[dbo].[System_Alerts]
ORDER BY 1;

-- Table: System_Notifications
-- Export to: extracted_data/System_Notifications.csv
SELECT *
FROM [Climasys-00010].[dbo].[System_Notifications]
ORDER BY 1;

-- Table: System_Audit
-- Export to: extracted_data/System_Audit.csv
SELECT *
FROM [Climasys-00010].[dbo].[System_Audit]
ORDER BY 1;

-- Table: SMS_Master
-- Export to: extracted_data/SMS_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[SMS_Master]
ORDER BY 1;

-- Table: Email_Master
-- Export to: extracted_data/Email_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Email_Master]
ORDER BY 1;

-- Table: Notification_Master
-- Export to: extracted_data/Notification_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Notification_Master]
ORDER BY 1;

-- Table: Reminder_Master
-- Export to: extracted_data/Reminder_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Reminder_Master]
ORDER BY 1;

-- Table: Communication_Logs
-- Export to: extracted_data/Communication_Logs.csv
SELECT *
FROM [Climasys-00010].[dbo].[Communication_Logs]
ORDER BY 1;

-- Table: Message_Templates
-- Export to: extracted_data/Message_Templates.csv
SELECT *
FROM [Climasys-00010].[dbo].[Message_Templates]
ORDER BY 1;

-- Table: Communication_Settings
-- Export to: extracted_data/Communication_Settings.csv
SELECT *
FROM [Climasys-00010].[dbo].[Communication_Settings]
ORDER BY 1;

-- Table: Report_Master
-- Export to: extracted_data/Report_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Report_Master]
ORDER BY 1;

-- Table: Report_Details
-- Export to: extracted_data/Report_Details.csv
SELECT *
FROM [Climasys-00010].[dbo].[Report_Details]
ORDER BY 1;

-- Table: Report_Schedules
-- Export to: extracted_data/Report_Schedules.csv
SELECT *
FROM [Climasys-00010].[dbo].[Report_Schedules]
ORDER BY 1;

-- Table: Report_History
-- Export to: extracted_data/Report_History.csv
SELECT *
FROM [Climasys-00010].[dbo].[Report_History]
ORDER BY 1;

-- Table: Analytics_Data
-- Export to: extracted_data/Analytics_Data.csv
SELECT *
FROM [Climasys-00010].[dbo].[Analytics_Data]
ORDER BY 1;

-- Table: Dashboard_Config
-- Export to: extracted_data/Dashboard_Config.csv
SELECT *
FROM [Climasys-00010].[dbo].[Dashboard_Config]
ORDER BY 1;

-- Table: KPI_Master
-- Export to: extracted_data/KPI_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[KPI_Master]
ORDER BY 1;

-- Table: Performance_Metrics
-- Export to: extracted_data/Performance_Metrics.csv
SELECT *
FROM [Climasys-00010].[dbo].[Performance_Metrics]
ORDER BY 1;

-- Table: Document_Master
-- Export to: extracted_data/Document_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Document_Master]
ORDER BY 1;

-- Table: Document_Categories
-- Export to: extracted_data/Document_Categories.csv
SELECT *
FROM [Climasys-00010].[dbo].[Document_Categories]
ORDER BY 1;

-- Table: Document_Versions
-- Export to: extracted_data/Document_Versions.csv
SELECT *
FROM [Climasys-00010].[dbo].[Document_Versions]
ORDER BY 1;

-- Table: Document_Access
-- Export to: extracted_data/Document_Access.csv
SELECT *
FROM [Climasys-00010].[dbo].[Document_Access]
ORDER BY 1;

-- Table: Document_Sharing
-- Export to: extracted_data/Document_Sharing.csv
SELECT *
FROM [Climasys-00010].[dbo].[Document_Sharing]
ORDER BY 1;

-- Table: Document_Archive
-- Export to: extracted_data/Document_Archive.csv
SELECT *
FROM [Climasys-00010].[dbo].[Document_Archive]
ORDER BY 1;

-- Table: Document_Backup
-- Export to: extracted_data/Document_Backup.csv
SELECT *
FROM [Climasys-00010].[dbo].[Document_Backup]
ORDER BY 1;

-- Table: Inventory_Master
-- Export to: extracted_data/Inventory_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Inventory_Master]
ORDER BY 1;

-- Table: Inventory_Items
-- Export to: extracted_data/Inventory_Items.csv
SELECT *
FROM [Climasys-00010].[dbo].[Inventory_Items]
ORDER BY 1;

-- Table: Inventory_Stock
-- Export to: extracted_data/Inventory_Stock.csv
SELECT *
FROM [Climasys-00010].[dbo].[Inventory_Stock]
ORDER BY 1;

-- Table: Inventory_Movements
-- Export to: extracted_data/Inventory_Movements.csv
SELECT *
FROM [Climasys-00010].[dbo].[Inventory_Movements]
ORDER BY 1;

-- Table: Inventory_Orders
-- Export to: extracted_data/Inventory_Orders.csv
SELECT *
FROM [Climasys-00010].[dbo].[Inventory_Orders]
ORDER BY 1;

-- Table: Inventory_Receipts
-- Export to: extracted_data/Inventory_Receipts.csv
SELECT *
FROM [Climasys-00010].[dbo].[Inventory_Receipts]
ORDER BY 1;

-- Table: Inventory_Issues
-- Export to: extracted_data/Inventory_Issues.csv
SELECT *
FROM [Climasys-00010].[dbo].[Inventory_Issues]
ORDER BY 1;

-- Table: Inventory_Returns
-- Export to: extracted_data/Inventory_Returns.csv
SELECT *
FROM [Climasys-00010].[dbo].[Inventory_Returns]
ORDER BY 1;

-- Table: Equipment_Master
-- Export to: extracted_data/Equipment_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Equipment_Master]
ORDER BY 1;

-- Table: Equipment_Categories
-- Export to: extracted_data/Equipment_Categories.csv
SELECT *
FROM [Climasys-00010].[dbo].[Equipment_Categories]
ORDER BY 1;

-- Table: Equipment_Maintenance
-- Export to: extracted_data/Equipment_Maintenance.csv
SELECT *
FROM [Climasys-00010].[dbo].[Equipment_Maintenance]
ORDER BY 1;

-- Table: Equipment_Calibration
-- Export to: extracted_data/Equipment_Calibration.csv
SELECT *
FROM [Climasys-00010].[dbo].[Equipment_Calibration]
ORDER BY 1;

-- Table: Equipment_History
-- Export to: extracted_data/Equipment_History.csv
SELECT *
FROM [Climasys-00010].[dbo].[Equipment_History]
ORDER BY 1;

-- Table: Asset_Master
-- Export to: extracted_data/Asset_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Asset_Master]
ORDER BY 1;

-- Table: Asset_Depreciation
-- Export to: extracted_data/Asset_Depreciation.csv
SELECT *
FROM [Climasys-00010].[dbo].[Asset_Depreciation]
ORDER BY 1;

-- Table: Training_Master
-- Export to: extracted_data/Training_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Training_Master]
ORDER BY 1;

-- Table: Training_Modules
-- Export to: extracted_data/Training_Modules.csv
SELECT *
FROM [Climasys-00010].[dbo].[Training_Modules]
ORDER BY 1;

-- Table: Training_Sessions
-- Export to: extracted_data/Training_Sessions.csv
SELECT *
FROM [Climasys-00010].[dbo].[Training_Sessions]
ORDER BY 1;

-- Table: Training_Records
-- Export to: extracted_data/Training_Records.csv
SELECT *
FROM [Climasys-00010].[dbo].[Training_Records]
ORDER BY 1;

-- Table: Education_Master
-- Export to: extracted_data/Education_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Education_Master]
ORDER BY 1;

-- Table: Certification_Master
-- Export to: extracted_data/Certification_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Certification_Master]
ORDER BY 1;

-- Table: Skill_Master
-- Export to: extracted_data/Skill_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Skill_Master]
ORDER BY 1;

-- Table: Quality_Standards
-- Export to: extracted_data/Quality_Standards.csv
SELECT *
FROM [Climasys-00010].[dbo].[Quality_Standards]
ORDER BY 1;

-- Table: Compliance_Checklist
-- Export to: extracted_data/Compliance_Checklist.csv
SELECT *
FROM [Climasys-00010].[dbo].[Compliance_Checklist]
ORDER BY 1;

-- Table: Audit_Master
-- Export to: extracted_data/Audit_Master.csv
SELECT *
FROM [Climasys-00010].[dbo].[Audit_Master]
ORDER BY 1;

-- Table: Audit_Details
-- Export to: extracted_data/Audit_Details.csv
SELECT *
FROM [Climasys-00010].[dbo].[Audit_Details]
ORDER BY 1;

-- Table: Compliance_Reports
-- Export to: extracted_data/Compliance_Reports.csv
SELECT *
FROM [Climasys-00010].[dbo].[Compliance_Reports]
ORDER BY 1;

-- Table: Quality_Metrics
-- Export to: extracted_data/Quality_Metrics.csv
SELECT *
FROM [Climasys-00010].[dbo].[Quality_Metrics]
ORDER BY 1;

-- Table: Regulatory_Requirements
-- Export to: extracted_data/Regulatory_Requirements.csv
SELECT *
FROM [Climasys-00010].[dbo].[Regulatory_Requirements]
ORDER BY 1;

-- Table: Emergency_Contacts
-- Export to: extracted_data/Emergency_Contacts.csv
SELECT *
FROM [Climasys-00010].[dbo].[Emergency_Contacts]
ORDER BY 1;

-- Table: Emergency_Procedures
-- Export to: extracted_data/Emergency_Procedures.csv
SELECT *
FROM [Climasys-00010].[dbo].[Emergency_Procedures]
ORDER BY 1;

-- Table: Disaster_Plan
-- Export to: extracted_data/Disaster_Plan.csv
SELECT *
FROM [Climasys-00010].[dbo].[Disaster_Plan]
ORDER BY 1;

-- Table: Emergency_Logs
-- Export to: extracted_data/Emergency_Logs.csv
SELECT *
FROM [Climasys-00010].[dbo].[Emergency_Logs]
ORDER BY 1;

-- Table: Crisis_Management
-- Export to: extracted_data/Crisis_Management.csv
SELECT *
FROM [Climasys-00010].[dbo].[Crisis_Management]
ORDER BY 1;

-- Table: Emergency_Resources
-- Export to: extracted_data/Emergency_Resources.csv
SELECT *
FROM [Climasys-00010].[dbo].[Emergency_Resources]
ORDER BY 1;

-- Table: Emergency_Training
-- Export to: extracted_data/Emergency_Training.csv
SELECT *
FROM [Climasys-00010].[dbo].[Emergency_Training]
ORDER BY 1;

-- Table: Research_Projects
-- Export to: extracted_data/Research_Projects.csv
SELECT *
FROM [Climasys-00010].[dbo].[Research_Projects]
ORDER BY 1;

-- Table: Clinical_Trials
-- Export to: extracted_data/Clinical_Trials.csv
SELECT *
FROM [Climasys-00010].[dbo].[Clinical_Trials]
ORDER BY 1;

-- Table: Research_Data
-- Export to: extracted_data/Research_Data.csv
SELECT *
FROM [Climasys-00010].[dbo].[Research_Data]
ORDER BY 1;

-- Table: Research_Participants
-- Export to: extracted_data/Research_Participants.csv
SELECT *
FROM [Climasys-00010].[dbo].[Research_Participants]
ORDER BY 1;

-- Table: Research_Results
-- Export to: extracted_data/Research_Results.csv
SELECT *
FROM [Climasys-00010].[dbo].[Research_Results]
ORDER BY 1;

-- Table: Research_Publications
-- Export to: extracted_data/Research_Publications.csv
SELECT *
FROM [Climasys-00010].[dbo].[Research_Publications]
ORDER BY 1;

-- Table: Research_Grants
-- Export to: extracted_data/Research_Grants.csv
SELECT *
FROM [Climasys-00010].[dbo].[Research_Grants]
ORDER BY 1;

-- Table: Telemedicine_Sessions
-- Export to: extracted_data/Telemedicine_Sessions.csv
SELECT *
FROM [Climasys-00010].[dbo].[Telemedicine_Sessions]
ORDER BY 1;

-- Table: Video_Consultations
-- Export to: extracted_data/Video_Consultations.csv
SELECT *
FROM [Climasys-00010].[dbo].[Video_Consultations]
ORDER BY 1;

-- Table: Remote_Monitoring
-- Export to: extracted_data/Remote_Monitoring.csv
SELECT *
FROM [Climasys-00010].[dbo].[Remote_Monitoring]
ORDER BY 1;

-- Table: Digital_Prescriptions
-- Export to: extracted_data/Digital_Prescriptions.csv
SELECT *
FROM [Climasys-00010].[dbo].[Digital_Prescriptions]
ORDER BY 1;

-- Table: Online_Appointments
-- Export to: extracted_data/Online_Appointments.csv
SELECT *
FROM [Climasys-00010].[dbo].[Online_Appointments]
ORDER BY 1;

-- Table: Virtual_Clinic
-- Export to: extracted_data/Virtual_Clinic.csv
SELECT *
FROM [Climasys-00010].[dbo].[Virtual_Clinic]
ORDER BY 1;

-- Table: API_Logs
-- Export to: extracted_data/API_Logs.csv
SELECT *
FROM [Climasys-00010].[dbo].[API_Logs]
ORDER BY 1;

-- Table: Integration_Config
-- Export to: extracted_data/Integration_Config.csv
SELECT *
FROM [Climasys-00010].[dbo].[Integration_Config]
ORDER BY 1;

-- Table: Data_Sync
-- Export to: extracted_data/Data_Sync.csv
SELECT *
FROM [Climasys-00010].[dbo].[Data_Sync]
ORDER BY 1;

-- Table: External_Systems
-- Export to: extracted_data/External_Systems.csv
SELECT *
FROM [Climasys-00010].[dbo].[External_Systems]
ORDER BY 1;

-- Table: Webhook_Logs
-- Export to: extracted_data/Webhook_Logs.csv
SELECT *
FROM [Climasys-00010].[dbo].[Webhook_Logs]
ORDER BY 1;

-- Table: Third_Party_Integrations
-- Export to: extracted_data/Third_Party_Integrations.csv
SELECT *
FROM [Climasys-00010].[dbo].[Third_Party_Integrations]
ORDER BY 1;

-- Table: Data_Exchange
-- Export to: extracted_data/Data_Exchange.csv
SELECT *
FROM [Climasys-00010].[dbo].[Data_Exchange]
ORDER BY 1;

-- Table: Security_Logs
-- Export to: extracted_data/Security_Logs.csv
SELECT *
FROM [Climasys-00010].[dbo].[Security_Logs]
ORDER BY 1;

-- Table: Access_Control
-- Export to: extracted_data/Access_Control.csv
SELECT *
FROM [Climasys-00010].[dbo].[Access_Control]
ORDER BY 1;

-- Table: Permission_Matrix
-- Export to: extracted_data/Permission_Matrix.csv
SELECT *
FROM [Climasys-00010].[dbo].[Permission_Matrix]
ORDER BY 1;

-- Table: Security_Policies
-- Export to: extracted_data/Security_Policies.csv
SELECT *
FROM [Climasys-00010].[dbo].[Security_Policies]
ORDER BY 1;

-- Table: Authentication_Logs
-- Export to: extracted_data/Authentication_Logs.csv
SELECT *
FROM [Climasys-00010].[dbo].[Authentication_Logs]
ORDER BY 1;

-- Table: Authorization_Matrix
-- Export to: extracted_data/Authorization_Matrix.csv
SELECT *
FROM [Climasys-00010].[dbo].[Authorization_Matrix]
ORDER BY 1;

-- Table: Security_Incidents
-- Export to: extracted_data/Security_Incidents.csv
SELECT *
FROM [Climasys-00010].[dbo].[Security_Incidents]
ORDER BY 1;

-- Table: Backup_Schedule
-- Export to: extracted_data/Backup_Schedule.csv
SELECT *
FROM [Climasys-00010].[dbo].[Backup_Schedule]
ORDER BY 1;

-- Table: Backup_History
-- Export to: extracted_data/Backup_History.csv
SELECT *
FROM [Climasys-00010].[dbo].[Backup_History]
ORDER BY 1;

-- Table: Recovery_Procedures
-- Export to: extracted_data/Recovery_Procedures.csv
SELECT *
FROM [Climasys-00010].[dbo].[Recovery_Procedures]
ORDER BY 1;

-- Table: Data_Archive
-- Export to: extracted_data/Data_Archive.csv
SELECT *
FROM [Climasys-00010].[dbo].[Data_Archive]
ORDER BY 1;

-- Table: Backup_Verification
-- Export to: extracted_data/Backup_Verification.csv
SELECT *
FROM [Climasys-00010].[dbo].[Backup_Verification]
ORDER BY 1;

-- Table: Recovery_Testing
-- Export to: extracted_data/Recovery_Testing.csv
SELECT *
FROM [Climasys-00010].[dbo].[Recovery_Testing]
ORDER BY 1;

-- Table: Disaster_Recovery
-- Export to: extracted_data/Disaster_Recovery.csv
SELECT *
FROM [Climasys-00010].[dbo].[Disaster_Recovery]
ORDER BY 1;

-- Table: Performance_Metrics
-- Export to: extracted_data/Performance_Metrics.csv
SELECT *
FROM [Climasys-00010].[dbo].[Performance_Metrics]
ORDER BY 1;

-- Table: System_Monitoring
-- Export to: extracted_data/System_Monitoring.csv
SELECT *
FROM [Climasys-00010].[dbo].[System_Monitoring]
ORDER BY 1;

-- Table: Resource_Usage
-- Export to: extracted_data/Resource_Usage.csv
SELECT *
FROM [Climasys-00010].[dbo].[Resource_Usage]
ORDER BY 1;

-- Table: Performance_Alerts
-- Export to: extracted_data/Performance_Alerts.csv
SELECT *
FROM [Climasys-00010].[dbo].[Performance_Alerts]
ORDER BY 1;

-- Table: Capacity_Planning
-- Export to: extracted_data/Capacity_Planning.csv
SELECT *
FROM [Climasys-00010].[dbo].[Capacity_Planning]
ORDER BY 1;

-- Table: Load_Balancing
-- Export to: extracted_data/Load_Balancing.csv
SELECT *
FROM [Climasys-00010].[dbo].[Load_Balancing]
ORDER BY 1;

-- Table: Performance_Optimization
-- Export to: extracted_data/Performance_Optimization.csv
SELECT *
FROM [Climasys-00010].[dbo].[Performance_Optimization]
ORDER BY 1;

-- Table: Custom_Fields
-- Export to: extracted_data/Custom_Fields.csv
SELECT *
FROM [Climasys-00010].[dbo].[Custom_Fields]
ORDER BY 1;

-- Table: Custom_Forms
-- Export to: extracted_data/Custom_Forms.csv
SELECT *
FROM [Climasys-00010].[dbo].[Custom_Forms]
ORDER BY 1;

-- Table: Custom_Reports
-- Export to: extracted_data/Custom_Reports.csv
SELECT *
FROM [Climasys-00010].[dbo].[Custom_Reports]
ORDER BY 1;

-- Table: Custom_Workflows
-- Export to: extracted_data/Custom_Workflows.csv
SELECT *
FROM [Climasys-00010].[dbo].[Custom_Workflows]
ORDER BY 1;

-- Table: Extension_Modules
-- Export to: extracted_data/Extension_Modules.csv
SELECT *
FROM [Climasys-00010].[dbo].[Extension_Modules]
ORDER BY 1;

-- Table: Plugin_Config
-- Export to: extracted_data/Plugin_Config.csv
SELECT *
FROM [Climasys-00010].[dbo].[Plugin_Config]
ORDER BY 1;

-- Table: Custom_Validations
-- Export to: extracted_data/Custom_Validations.csv
SELECT *
FROM [Climasys-00010].[dbo].[Custom_Validations]
ORDER BY 1;
